[phases.setup]
nixPkgs = ["php", "composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "php bin/console cache:clear --env=prod --no-debug",
    "php bin/console doctrine:migrations:migrate --env=prod --no-interaction",
    "php bin/console assets:install public --env=prod"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
