services:
  - type: web
    name: mossair-symfony
    env: php
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
